[workspace]
members = ["error-code", "error-code-derive"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.94"
thiserror = "2.0.7"
http = "1.2.0"
error-code = { path = "./error-code" }
error-code-derive = { path = "./error-code-derive" }
